name: 编译部署

on:
    push:
        branches:
            - master

    # 这个选项可以使你手动在 Action tab 页面触发工作流
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 设置 Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: 拉取分支
              uses: actions/checkout@v4

            - name: 安装 pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: 10 # 或者你本地使用的版本
                  run_install: false

            - name: 设置 Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 25.x
                  cache: 'pnpm' # 自动处理 pnpm store 的缓存，无需手动写 cache 步骤


            - name: 安装依赖
              run: pnpm install --frozen-lockfile

            - name: 设置环境变量
              run: |
                  echo VITE_CDN_BASE=https://cdn.jsdmirror.com/gh/chzxxuanzheng/The-World-Of-Lee@pages/ >> $GITHUB_ENV

            - name: 构建
              run: pnpm build

            - name: 配置 Pages 环境
              uses: actions/configure-pages@v5

            - name: 上传构建产物
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./dist"

            - name: 部署到 GitHub Pages
              id: deployment
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: pages
                  folder: dist